#ifndef RADIO_INFO_H
#define RADIO_INFO_H

enum {
	RADIO_TIMESYNC_MSG = 200,
	RADIO_JOIN_REQ_MSG = 201,
	RADIO_JOIN_ANS_MSG = 202,
	RADIO_DATA_PKG_MSG = 203,
	RADIO_PC_MOTE_DATA = 204,
	RADIO_ASSIGNMENT_START_MSG = 205,
	RADIO_ASSIGNMENT_ACK_MSG = 206,
	RADIO_ASSIGNMENT_MSG = 207
};

#endif /* RADIO_INFO_H */
